### PR TITLE
Indexterm

### PR DESCRIPTION
**Pull request by miwie**
Corrected wrong occurances of 'indextermsee' to 'indexterm'

### CODE REVIEW

**Comment by xtaran** [comment]
Hi Michael,

please don't merge non-accepted commits from previous pull-requests when filing new pull requests.

You can reset your branch to our current state for that by using `git fetch && git reset --hard origin/master`. If you want access to your previous commits in the branch, you can see them with `git reflog`.

I'll use `git cherry-pick` for this case.

**Comment by miwie** [comment]
I apologise for the trouble caused :(

**Comment by xtaran** [comment]
No problem. I assume good faith and lack of knowledge about the expected workflow. :-)

**Comment by xtaran** [comment]
Actually this is a left-over from our previous publisher, too. We might want to recycle this macro name, too.

**Comment by xtaran** [comment]
The relevant lines changed in 9679487 (which seems to have been the core of this pull request) have been removed respectively changed differently in 0c9b22853a2cda56d3adb86e79be317582d983ea anyways, so closing this pull request.

**Pull request closed without merging**
